language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t younes-amine/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true younes-amine/docker-react npm run test
 
deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-312968458976"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
  aws_session_token: $AWS_SESSION_TOKEN
















