language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t younes-amine/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true younes-amine/docker-react npm run test
















