sudo: required
services:
  - docker

before_install:
  - docker build -t younes-amine/docker-react -f Dcokerfile.dev .
script:
  - docker run younes-amine/docker-react npm run test -- --coverage
















